### ISSUE TITLE
[BUG] `ctf queue` does not start solving

### ISSUE THREAD

**Issue by ent3r** [JohnHammond/katana#7]
What is this?
- [ ] Feature
- [x] Bug
- [ ] Improvement

**Please describe the issue**
When running `ctf queue first-grep--part-ii-485b43c` nothing happens. The command is ran, but the CLI says `0 units queued`. After waiting for 5 minutes nothing happens.

**In case of bug, what is supposed to happen?**
The command is ran successfully, and katana starts working. Hopefully managing to extract the flag.

**If possible, what CTF and/or task are you trying it on?**
PicoCTF, First Grep: Part II

**Output of `python -v` in virtualenv**
Python 3.7.5

**Version of katana**
The one where [this](https://github.com/JohnHammond/katana/commit/dd1c15c7285ed9b8c0b8284d8c9097345fe237d1) was the latest commit.

**Did you follow the instructions to install?**
Yes

**Anything else?**
I am running katana in the virtualenv using `python -m katana -c configs/picoctf.ini --force`.

My config file looks like this:
```ini
[DEFAULT]
download=yes

[manager]
flag-format=picoCTF{.*?}

[ctf]
provider=pico
url=https://2019game.picoctf.com
username=[REDACTED]
password=[REDACTED]
auto-submit=yes
```
It is basically a copy of [your example](https://youtu.be/BEFMOG8R3ag?t=447) in your walkthrough.

I am running this in WSL.

I have ran this on other challenges where it worked.

**Comment by calebstewart** [comment]
This is because there is nothing to queue. We should add a message indicating this, but that challenge has no attached files, and the default is to not queue the description, and only queue attached files. In this case, the file is not attached. The URI of the file on the server is mentioned, but Katana has no way of knowing how to grab that file.
